baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Anton Lee'
theme = 'native-ish'

[markup]
  [markup.highlight]
    style="github-dark"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]

[params]
  math = true
